apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-access-control
  namespace: fint-core
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-access-control:latest
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx525M'
  resources:
    limits:
      memory: "800Mi"
      cpu: "1"
    requests:
      memory: "500Mi"
      cpu: "100m"